version: '3'

services:
  market:
    container_name: market
    image: gqbot:market
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./config.json:/app/config.json

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_NODENAME=my-rabbit
    ports:
      - 15672
      - 5672
