version: '3'

services:
  market:
    container_name: market
    image: gqbot:market
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./config.json:/app/config.json

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_NODENAME=my-rabbit
    ports:
      - 15672
      - 5672

  jupyter:
    image: gqbot:jupyter
    build:
      context: ./docker/jupyter
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./code:/code
    ports:
      - "6000:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
  vscode:
    image: gqbot:vscode
    build:
      context: ./docker/vscode
      dockerfile:  Dockerfile
    volumes:
      - ./data:/data
      - ./code:/code
    ports:
      - "6000:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
